bot:
  token: ${TOKEN}
  logChannelId: ${LOG_CHANNEL_ID}
  activationKey: ${ACTIVATION_KEY}

spring:
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./generator_bot_db
    username: sa
    password: password
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 20
      auto-commit: true
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
